import "./add blank field"
import "./add field"
import "./add fields"
import "./create embed"
import "./set author"
import "./set color"
import "./set description"
import "./set thumbnail"
import "./set title"
import "./set image"
import "./set footer"
import "./set thumbnail"
import "./add timestamp"
import "./send embed"
import "./simple embed"