import "./new_dashboard"
import "./variables"
import "./new_text_input"
import "./add_boolean_input"
import "./add_inputs"
import "./add_dropdown_input"
import "./new_couple.js"
import "./add_colour_input.js"