import "./create_webhook";
import "./edit_webhook";
import "./webhook_id";
import "./webhook_token";
import "./get_webhook_then";
import "./get_webhook_then_edit";
import "./webhook_send";
import "./create_webhook_customized"
import "./webhook_send_created"
import "./webhook_send_mentions"
import "./webhook_send_created_mentions"
import "./send_created_customized"
import "./send_webhook_with_name"