import "./create_channel";
import "./get_channel";
import "./send_channel";
import "./send_wait_reply";
import "./send_wait_reply_value";
import "./delete_channel";
import "./get_all_channel_then";
import "./get_all_channel_then_channel";
import "./set_channel_permissions";
import "./set_perms";
import "./set_perms_parent";
import "./set_slowmode";
import "./is_channel_nsfw";
import "./channel_exist";
import "./reply_message";
import "./reply_mentioned_channel";
import "./reply_mentioned_member";
import "./reply_mentioned_role";
import "./get_all_channel_channel_name"
import "./ahq_channel_name"
import "./id_of_channel"
import "./guild_of_channel"
import "./id_of_channel_parent"
import "./id_of_last_message"
import "./topic_of_channel"
import "./set_afk_channel"
import "./set_afk_channel_time"
