import "./sendTestconsole"
import "./beginJimpEdits"
import "./saveImageTo"
import "./sendImage"
import "./sendImageMSG"
import "./sendImagerow"
import "./sendImageMSGrow"
//the return on april fools
import "./banana"
//--no banana block or no merge :(--
//he is back
//nvm april eneddd and i forgor💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀
import "./beginJimpImage"
import "./nullBlock"
import "./undefinedBlock"
import "./webBlocks"
import "./sendTyping"
import "./sendTypingChannel"
import "./s4duptime"
import "./other_err"
import "./text"
import "./chartsAndGraphs"
import "./experiments"
import "./misc"
import "./slashandbutton"
import "./Objects"
import "./tests"
import "./base"
import "./minecraft"
import "./theroblox"
import "./messages_blocks"
import "./voice"
import "./miscblocks"
import "./sendImageFinal"
import "./ffmpeg"
import "./themeBlocks"