import Blockly from "blockly/core";
Blockly.Blocks["jg_api_express_main"] = {
    init: function () {
        this.jsonInit(
            {
                "message0": "Create express site on port %3 then %1 %2",
                "colour": "#4abc79",
                "args0": [
                    {
                        "type": "input_dummy"
                    },
                    {
                        "type": "input_statement",
                        "name": "STATEMENTS"
                    },
                    {
                        "type": "input_value",
                        "name": "PORT",
                        "check": "Number"
                    }
                ],
                "tooltip": "Start a webserver on a certain port."
            }
        );
    }
};

Blockly.JavaScript["jg_api_express_main"] = function (block) {
    const statements = Blockly.JavaScript.statementToCode(block, "STATEMENTS");
    const port = Blockly.JavaScript.valueToCode(block, "PORT", Blockly.JavaScript.ORDER_ATOMIC);
    const code = `let S4D_APP_EXPRESS = require('express')
let S4D_APP_EXPRESS_bodyParser = require('body-parser');
let S4D_APP_EXPRESS_cors = require('cors');
let S4D_APP_EXPRESS_path = require('path');
let S4D_APP_EXPRESS_app = S4D_APP_EXPRESS();
let S4D_APP_EXPRESS_port = ${port};

S4D_APP_EXPRESS_app.use(S4D_APP_EXPRESS_cors());
S4D_APP_EXPRESS_app.use(S4D_APP_EXPRESS_bodyParser.urlencoded({
    extended: false
}));
S4D_APP_EXPRESS_app.use(S4D_APP_EXPRESS_bodyParser.json());
  
${statements}

// Generated by Scratch For Discord
// Blocks made on Scratch For Anything
S4D_APP_EXPRESS_app.listen(S4D_APP_EXPRESS_port, () => console.log('Listening on port ' + S4D_APP_EXPRESS_port));`;
    return code;
};