import "./bot_ping";
import "./bot_server_count";
import "./login";
import "./on_connected";
import "./set_bot_game";
import "./get_bot";
import "./s4d_bot_shutdown";
import "./set_bot_stream";
import "./set_bot_stream_text";
import "./bot_amout";
import "./start_antispam";
import "./change";
import "./bot_startup_time"