import "./double_dropdown"
import "./type_change"
import "./delete_input"
import "./validator"
import "./onchange"
import "./validator2"
import "./custom_restriction_name"
import "./working_checkbox_mutator"